# input/output representation
root_dir: "../data/"
input_style: "binned"  # "normed_raw", "log1p", or "binned"
output_style: "binned"  # "normed_raw", "log1p", or "binned"
input_emb_style: "continuous"  # "category" or "continuous" or "scaling"

pad_token: "<pad>"
max_seq_len: 3001

seed: 0
dataset_name: "ms"
do_train: true
load_model: "save/scGPT_human"
mask_ratio: 0.0
epochs: 10
n_bins: 51
MVC: false
ecs_thres: 0.0
dab_weight: 0.0
lr: 1e-4
batch_size: 32
layer_size: 128
nlayers: 4
nhead: 4
dropout: 0.2
schedule_ratio: 0.9
save_eval_interval: 5
fast_transformer: true
pre_norm: false
amp: true
include_zero_gene: false
freeze: false
DSBN: false

